config/routes.rb
ResponseMonster::Application.routes.draw do

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/types"

  root to: "users#home"

  resources :users

  resources :courses do
    member do
      get 'add'
      get 'drop'
    end
    resources :surveys, except: :index do
      member do
        get 'activate'
        get 'deactivate'
        get 'summary'
        get 'login'
        post 'check'
        post 'newgrade'
        get 'grade'
        get 'stats'
      end
      resources :polls do
        resources :answers
      end
      resources :assessments do
        resources :responses
      end
    end
  end

  resources :responses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new', via: :get
  match '/signin',  to: 'sessions#create', via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: 'StaticPages#about'
  match '/home',    to: 'users#home'
  match '/types',   to: 'StaticPages#types'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :enrollments, dependent: :destroy
  has_many :courses, through: :enrollments
  has_many :assessments, dependent: :destroy
  has_many :responses, through: :assessments, dependent: :destroy
  has_secure_password
  attr_accessible :email, 
            :first_name, 
            :last_name, 
            :password, 
            :password_confirmation

  validates(:first_name, :last_name, presence: true, length: { maximum: 50 })
  validates(:password, presence: true, length: { minimum: 6 })
  validates(:password_confirmation, presence: true)
  VALID_EMAIL_REGEX = /@/i
  validates(:email, presence: true, 
            uniqueness: { case_sensitive: false }, 
            format: { with: VALID_EMAIL_REGEX })
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

#  def self.find_last_assessment(survey, user)
#    user.assessments.each do |assessment|
#      if assessment.survey_id == survey.id
#        return assessment
#      end
#    end
#  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, except: [:new, :create]
  before_filter :check_correct_user, only: [:show, :edit]
  before_filter :admin_user, only: [:index]

  def index
    @users = User.all

    respond_to do |format|
      format.html 
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html 
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to ResponseMonster!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def home
    if current_user
      @enrolled = current_user.courses.all
      @taught = Course.where(teacher_id: current_user.id)
      @open_surveys = Survey.where(course_id: current_user.courses + @taught,
                                   is_active: true)
      render 'home'
    else
      render 'sessions/new'
    end
  end

  private
    def check_correct_user
      @user = User.find(params[:id])
      if @user != current_user and not current_user.admin?
        redirect_to root_path, notice: "You cannot view other users' profiles."
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_enrolled_classes.html.haml
%td.half-cell
  %h3 Enrolled Classes
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Name
        %th Title
        %th Section
        %th Term
        %th Teacher
        - if is_admin?
          %th
            Edit
    %tbody
      - @enrolled.each do |course|
        %tr
          %td=link_to course.name, course
          %td=course.title
          %td=course.section
          %td
            - if Date.new(Date.today.year, 8, 1)
              Fall
            - else
              Spring
          %td= "#{User.find_by_id(course.teacher_id).first_name} #{User.find_by_id(course.teacher_id).last_name}"
          - if is_admin?
            %td
              = link_to "Edit", edit_course_path(course), class: "btn"

app/views/users/_form.html.haml
#form
  = form_for(@user) do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= pluralize(@user.errors.count, "Error")
        Prohibited this user from being saved:

        %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

    .field
      = f.text_field :first_name, autofocus: "autofocus", placeholder: "First Name"
    .field
      = f.text_field :last_name, placeholder: "Last Name"
    .field
      = f.text_field :email, placeholder: "Email"
    .field
      = f.password_field :password, placeholder: "Password"
    .field
      = f.password_field :password_confirmation, placeholder: "Password Confirmation"
    .actions
      %input.btn.btn-large.btn-primary{ type: "submit", value: "Sign me up!" }

app/views/users/_teaching_classes.html.haml
- if !@taught.empty?
  %td.half-cell
    %h3 Classes you teach
    %table.table.table-hover.table-condensed
      %thead
        %tr
          %th Name
          %th Title
          %th Section
          %th Term
          %th.hidden-phone Students
          - if is_admin?
            %th
              Edit
      %tbody
        - @taught.each do |course|
          - if course.teacher_id == current_user.id
            %tr
              %td=link_to course.name, course
              %td=course.title
              %td=course.section
              %td
                - if Date.new(Date.today.year, 8, 1)
                  Fall
                - else
                  Spring
              %td.hidden-phone=course.users.count
              - if is_admin?
                %td
                  = link_to "Edit", edit_course_path(course), class: "btn"

app/views/users/edit.html.haml
%h2
  Editing user

= render 'form'

= link_to 'Show', @user
%br
= link_to 'Back', users_path

app/views/users/home.html.haml
.row
  .span12
    %h1
      ResponseMonster
    %br
    - if !@open_surveys.empty?
      %h3 Open surveys in your classes
      %table.table.table-hover.table-condensed
        %thead
          %tr
            %th Class
            %th Survey
            %th Action
        %tbody
          - @open_surveys.each do |survey|
            - if @taught.include? survey.course
              %tr
                %td= link_to survey.course.name, course_path(survey.course)
                %td= survey.name
                %td
                  = link_to "View Quiz", course_survey_path(survey.course, survey), class: "btn"
                  = link_to "See Responses", course_survey_assessments_path(survey.course, survey), class: "btn"
                  = link_to "See Stats", stats_course_survey_path(survey.course, survey), class: "btn"
                  = link_to "Deactive Survey", deactivate_course_survey_path(survey.course, survey), class: "btn"
            - else
              %tr
                %td= link_to survey.course.name, course_path(survey.course)
                %td= survey.name
                - if survey.end_time.nil?
                  %td Unknown
                - else
                  %td=  survey.end_time
                %td
                  = link_to "Take Quiz", login_course_survey_path(survey.course, survey), class: "btn"
.row
  - if !@enrolled.empty? && !@taught.empty?
    .span6
      = render 'enrolled_classes'
    .span6
      = render 'teaching_classes'
  - elsif @taught.empty?
    .span12
      = render 'enrolled_classes'
  - else
    .span12
      = render 'teaching_classes'
.row
  .span12
    .btn-toolbar
      - if is_admin?
        = link_to "Create Course", new_course_path, class: "btn"
      = link_to "Enroll/Drop Classes", courses_path, class: "btn"

app/views/users/index.html.haml
%h2
  Listing users

%table.table.table-hover.table-condensed
  %tr
    %th
      Email
    %th
      First name
    %th
      Last name
    %th
      Actions
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.first_name
      %td= user.last_name
      %td= link_to 'Show', user, class: "btn"
      %td= link_to 'Edit', edit_user_path(user), class: "btn"
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn"
%br

app/views/users/new.html.haml
.row
  .span6.offset5
    %h2
      New user

    = render 'form'

    = link_to 'Back', users_path, class: 'btn btn-large btn-primary'

app/views/users/show.html.haml
%h2=@user.first_name + " " + @user.last_name
%h3=@user.email
.center
  =link_to 'Edit', edit_user_path(@user), class: "btn"
  =link_to 'Back', users_path, class: "btn"
%br
- if is_admin?
  %table.wide
    %tr
      - if !@user.courses.empty? || Course.where(teacher_id: @user.id).empty?
        %td.half-cell
          %h2="#{@user.first_name}'s classes"
          %table.table.table-hover.table-condensed
            %thead
              %tr
                %th Name
                %th Title
                %th Section
                %th Term
                %th Teacher
                - if is_admin?
                  %th
                    Edit
            %tbody
              - @user.courses.each do |course|
                %tr
                  %td=link_to course.name, course
                  %td=course.title
                  %td=course.section
                  %td
                    - if Date.new(Date.today.year, 8, 1)
                      Fall
                    - else
                      Spring
                  %td= "#{User.find_by_id(course.teacher_id).first_name} #{User.find_by_id(course.teacher_id).last_name}"
                  - if is_admin?
                    %td
                      = link_to "Edit", edit_course_path(course), class: "btn"