config/routes.rb
ResponseMonster::Application.routes.draw do

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/types"

  root to: "users#home"

  resources :users

  resources :courses do
    member do
      get 'add'
      get 'drop'
    end
    resources :surveys, except: :index do
      member do
        get 'activate'
        get 'deactivate'
        get 'summary'
        get 'login'
        post 'check'
        post 'newgrade'
        get 'grade'
        get 'stats'
      end
      resources :polls do
        resources :answers
      end
      resources :assessments do
        resources :responses
      end
    end
  end

  resources :responses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new', via: :get
  match '/signin',  to: 'sessions#create', via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: 'StaticPages#about'
  match '/home',    to: 'users#home'
  match '/types',   to: 'StaticPages#types'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to      :course
  has_many        :polls, dependent: :destroy
  has_many        :assessments, dependent: :destroy
  has_many        :users, through: :assessments
  attr_accessible :end_time, 
                        :name, 
                        :start_time, 
                        :is_active, 
                        :polls_attributes, 
                        :attempts_allowed,
                        :total_points,
                        :password

  validates(:name, presence: true)

  accepts_nested_attributes_for :polls, 
                                reject_if: lambda { |question| question[:question_text].blank? },
                                allow_destroy: true

  def toggle_survey(survey)
    survey.toggle!(:is_active)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  require 'debugger'
  before_filter :authenticate
  before_filter(except: [:summary, :login, :check]) { |controller| controller.check_permissions(Course.find(params[:course_id])) }
  before_filter :admin_user, only: [:index]

  def show
    @survey = Survey.find(params[:id])
    @course = @survey.course
    @times_submitted = @survey.assessments.where(user_id: current_user.id).length
    @responses = []
    @survey.polls.each do |poll|
      poll.answers.each do |answer|
        @responses << Response.new
      end
    end
  end

  def new
    @survey = Survey.new
    @course = Course.find(params[:course_id])
  end

  def edit
    @survey = Survey.find(params[:id])
    @course = Course.find(params[:course_id])
  end

  def create
    @course = Course.find(params[:course_id])
    @survey = @course.surveys.new(params[:survey])

    total = 0
    @survey.polls.each do |poll|
      total += poll.points
    end
    @survey.total_points = total

    if @survey.save
      redirect_to course_path(@course), notice: "Survey was successfully created"
    else
      render new_course_survey_path(@course), notice: "There were some errors"
    end
  end

  def update
    @survey = Survey.find(params[:id])
    @course = @survey.course

    if @survey.update_attributes(params[:survey])
      redirect_to course_path(@course), notice: 'Survey was successfully updated'
    else
      render "edit", notice: "There were some errors"
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @course = @survey.course

    if @survey.destroy
      redirect_to course_path(@course), notice: "Survey successfully deleted"
    else
      redirect_to course_path(@course), notice: "Survey was not deleted"
    end
  end

  def activate
    @survey = Survey.find(params[:id])
    @course = @survey.course
    if @survey.toggle_survey(@survey)
      redirect_to course_path(@course), notice: "Activated survey"
    else
      redirect_to course_path(@course), notice: "Could not activate survey"
    end
  end

  def deactivate
    @survey = Survey.find(params[:id])
    @course = @survey.course
    if @survey.toggle_survey(@survey)
      redirect_to course_path(@course), notice: "Deactivated survey"
    else
      redirect_to course_path(@course), notice: "Could not deactivate survey"
    end
  end

  def login
    @survey = Survey.find(params[:id])
    @course = @survey.course
    if @course.teacher_id == current_user.id || is_admin? || @survey.password.nil? || @survey.password.empty?
      redirect_to new_course_survey_assessment_path(@course, @survey)
    end
  end

  def stats
    @survey = Survey.find(params[:id])
    @course = @survey.course
    @assessments = @survey.assessments

    # get all the scores
    graph_data = @assessments.collect{|a| a.score}
    # isolate unique scores
    graph_cats = []
    graph_data.each{|g| graph_cats << g unless g.in? graph_cats}
    # sort isolated scores to make grapher happy
    graph_cats = graph_cats.sort
    # count individual scores
    graph_map = graph_cats.collect{|g| graph_data.select{|y| y==g}.length}
    graph_cats = graph_cats.each{|g| String(g)}

    @gd_chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:type] = "column"
      f.options[:title][:text] = "Grade Distribution"
      f.series(showInLegend: false, data: graph_map)
      f.options[:xAxis][:categories] = graph_cats
      f.options[:xAxis][:title] = { text: "Grades" }
      f.options[:yAxis][:allowDecimals] = false
      f.options[:yAxis][:title] = { text: "Amount" }
    end
    @answer_charts = []
    @survey.polls.each do |p|
      # Get answer data for each
      answer_data = p.answers.collect{|a| [a.answer_text, Response.where(choiceId: a.id).length]}
      a_chart = LazyHighCharts::HighChart.new('graph') do |f|
        f.options[:chart][:type] = "pie"
        f.options[:title][:text] = "<b>" + p.question_text + "</b>"
        f.options[:plotOptions][:pie] = { allowPointSelect: true }
        f.series(type: "pie", name: "Count", data: answer_data)
      end
      @answer_charts << a_chart
    end

  end

  def check
    @survey = Survey.find(params[:id])
    @course = @survey.course
    if params["pass"][:password] && params["pass"][:password] == @survey.password
      redirect_to new_course_survey_assessment_path(@course, @survey)
    else
      flash.now[:error] = "The password you entered was incorrect"
      render "login"
    end
  end

end

####################
# Depreciated methods
####################
#  def summary
#    @survey = Survey.find(params[:id])
#    @course = @survey.course
#    @polls = @survey.polls.all
#    if !params[:assessment_id].nil?
#      @student_assessment = Assessment.find(params[:assessment_id])
#    else
#      @student_assessment = Assessment.where(user_id: current_user.id, survey_id: @survey.id).first
#    end
#    @grades = []
#    if !params[:assessment_id].nil? && current_user.id == @course.teacher_id
#      @assessment = Assessment.find(params[:assessment_id])
#    end
#    @responses = current_user.responses.all
#  end


#  def grade
#    @survey = Survey.find(params[:id])
#    @course = @survey.course
#    @assessments = @survey.assessments
#  end
#
#  def newgrade
#    assessment = Assessment.find(params[:assessment_id])
#    @survey = assessment.survey
#    changing = []
#    params.keys[2..-7].each do |key|
#      response = Response.find(key.split("s")[1])
#      response.points = params[key]
#      response.save
#    end
#    assessment.score = 0
#    assessment.responses.each do |response|
#      assessment.score += response.points
#    end
#    assessment.is_graded = true
#    assessment.save
#    redirect_to grade_course_survey_path(@survey.course, @survey), notice: "Successfully graded #{assessment.user.first_name}'s quiz"
#  end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer_fields.html.haml
.subform
  .well
    %fieldset
      = f.label :answer_text
      = f.text_field :answer_text
      %label.checkbox
        Correct Answer?
        = f.check_box :is_right
      = link_to_remove_fields "Remove Answer", f

app/views/surveys/_form.html.haml
= javascript_include_tag "add_and_remove_helpers"
= form_for([@course, @survey]) do |f|
  - if @survey.errors.any?
    #error_explanation
      %h3= pluralize(@survey.errors.count, "Error")
      Prohibited this survey from being saved:
        
      %ul
      - @survey.errors.full_messages.each do |msg|
        %li= msg

  = f.label :name, "Survey Name, eg: Quiz 1"
  = f.text_field :name, autofocus: "autofocus"
  = f.label :attempts_allowed, "Attempts Allowed, Enter 0 for unlimited attempts"
  = f.number_field :attempts_allowed, required: true, min: 0
  = f.label :password, "Password, If a password isn't needed, leave these fields blank"
  = f.text_field :password

  .questions
    = f.fields_for :polls do |builder|
      = render 'poll_fields', :f => builder 
    %br
    %br
    // Need to figure out how to make this a better button
    = link_to_add_fields "Add Question", f, :polls

  %br
  .actions
    %input.btn.btn-large.btn-primary{ type: "submit", value: "Save Survey" }

app/views/surveys/_poll_fields.html.haml
.subform
  %h3 Question
  .well
    = f.label :question_text, "Question Text, eg: What is my favorite color"
    = f.text_field :question_text
    %br
    Question Type, read #{link_to 'This', types_path, target: "_blank"} for more info
    %br
    = f.select :answer_type, "<option>Multiple Choice</option><option>Short Answer</option><option>Code</option><option>Essay</option>".html_safe
    %br
    Should users only be allowed to select one answer?
    %br
    = f.select :is_radio, "<option>Yes</option><option>No</option>".html_safe
    %br
    = f.label :points, "How many points is this worth?"
    = f.number_field :points, required: true, min: 0
    %h3 Answer(s)
    = f.fields_for :answers do |builder|
      = render 'answer_fields', f: builder
    .btn-toolbar
      = link_to_add_fields "Add Answer", f, :answers
      = link_to_remove_fields "Remove Question", f

app/views/surveys/_user_response.html.haml
= form_for("responses[]", url: { action: 'create', controller: 'responses', survey: params[:id] }) do |f|
  .well
    #surveyDetails
      %h3
        Details
      %p
        %b
          Name
        %br
        = @survey.name
        %br
        %b
          Attempts
        %br
        - if @survey.attempts_allowed.nil? || @survey.attempts_allowed == 0
          = @times_submitted
        - else
          = "#{@times_submitted} / #{@survey.attempts_allowed}"

  #surveyQuestions
    %h2
      Questions
    - @survey.polls.each do |poll|
      = poll.question_text
      - if !poll.answers.any?
        %br
        = text_field_tag "short_answer#{poll.id}"
        %br
      - poll.answers.each do |answer|
        .well
          - if poll.answer_type == "Multiple Choice"
            - if poll.is_radio == "Yes"
              = radio_button_tag "pollId#{poll.id}", answer.id
            - else
              = check_box_tag "pollId#{answer.id}", answer.id
            = answer.answer_text
  %input.btn.btn-large.btn-primary{ type: "submit", value: "Submit" }

app/views/surveys/edit.html.haml
%h2
  Editing survey

= render 'form'

= link_to 'Back', course_path(params[:course_id]), class: "btn"

app/views/surveys/grade.html.haml
%h2
  Assessments


%table.table
  %tr
    %th
      Name
    %th
      Time Submitted
    %th
      Score
    %th
      Grade
  - @assessments.each do |assessment|
    %tr
      %td
        = "#{assessment.user.first_name} #{assessment.user.last_name}"
      %td
        = assessment.created_at
      %td
        = "#{assessment.score} / #{assessment.survey.total_points}"
      %td
        = link_to "Grade", summary_course_survey_path(@course, @survey, assessment_id: assessment.id), class: "btn"

= link_to "Back", course_path(@course), class: "btn"

app/views/surveys/index.html.haml
%h2
  Listing surveys

%table
  %tr
    %th
    %th
    %th

  - @surveys.each do |survey|
    %tr
      %td
        = link_to 'Show', survey, class: "btn"
      %td
        = link_to 'Edit', edit_survey_path(survey), class: "btn"
      %td
        = link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn"

%br

= link_to 'New Survey', new_survey_path, class: "btn"

app/views/surveys/login.html.haml
.span4.offset5
  #form
    = form_for(:pass, url: { action: "check" } ) do |f|
      %p
        = f.label :password
        %br
        = f.text_field :password, autofocus: "autofocus"
      %br
      %input.btn.btn-large.btn-primary{ type: "submit", value: "Proceed" }

app/views/surveys/new.html.haml
%h2
  New survey

= render 'form'

= link_to 'Back', course_path(params[:course_id]), class: "btn"

app/views/surveys/show.html.haml
%h2
  Survey

%br

#surveyDetails
  %h3
    Details
  %p
    %b
      Name
    %br
    = @survey.name

  = link_to "Edit Survey", edit_course_survey_path(@course, @survey), class: "btn pull-right"
  = link_to 'Back', course_path(@course), class: "btn pull-right"

  #surveyQuestions
    %h3
      Questions
    - @survey.polls.each do |poll|
      %table.table
        %thead
          %tr
            %td
              = poll.question_text
            %td
              Correct Answer?
            %td
              = "#{poll.points} points possible"
        - poll.answers.each do |answer|
          %tr
            %td
              = answer.answer_text
            %td
              = answer.is_right.to_s.capitalize
            %td
        %br

= link_to "Edit Survey", edit_course_survey_path(@course, @survey), class: "btn"
= link_to 'Back', course_path(@course), class: "btn"

app/views/surveys/stats.html.haml
%h2
  Survey Statistics

%br

%h3
  = @survey.name

%br
= high_chart("GradeDistribution", @gd_chart)
- x = 0
- @answer_charts.each do |a|
  = high_chart("ans_chart" + String(x+=1), a)

= link_to 'Back', course_path(@course), class: "btn"

app/views/surveys/summary.html.haml
%h2
  Summary

%h3
  = @survey.name
%br
%p
  Score:
  = "#{@student_assessment.score} / #{@survey.total_points}"

%h3
  Questions

- if !@assessment.nil?
  = form_for("grades[]", url: { action: "newgrade", assessment_id: @assessment.id } ) do |f|
    - @assessment.responses.each do |response|
      = response.poll.question_text
      .well
        - response.poll.answers.each do |answer|
          - if response.choiceId == answer.id && response.is_right
            .correct-answer= answer.answer_text
          - elsif response.choiceId == answer.id && !response.is_right
            .wrong-answer= answer.answer_text
          - else
            .not-picked-answer= answer.answer_text
        - if response.poll.answers.empty?
          = response.short_answer
          %br
        %br
        = f.label :points, "Points earned out of #{response.poll.points}"
        - if response.points.nil?
          = number_field_tag "points#{response.id}", 0, in: 0...response.poll.points+1
        - else
          = number_field_tag "points#{response.id}", response.points, in:0...response.poll.points+1
    = f.submit "Save Grades", class: "btn"
- else
  - @survey.polls.each do |poll|
    = poll.question_text
    %br
    .well
      - if poll.answers.any?
        - poll.answers.each do |answer|
          - @is_choice = false
          - @responses.each do |response|
            - if answer.id == response.choiceId
              - @is_choice = true
          - if @is_choice && answer.is_right?
            .correct-answer= answer.answer_text
          - elsif @is_choice && !answer.is_right?
            .wrong-answer= answer.answer_text
          - else
            .not-picked-answer= answer.answer_text
          %br
      - @responses.each do |response|
        - if response.poll_id == poll.id
          - if response.short_answer
            = response.short_answer
          -# elsif response.essay
          -# elsif response.code

= link_to "Back", course_path(@course), class: "btn"