config/routes.rb
ResponseMonster::Application.routes.draw do

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/types"

  root to: "users#home"

  resources :users

  resources :courses do
    member do
      get 'add'
      get 'drop'
    end
    resources :surveys, except: :index do
      member do
        get 'activate'
        get 'deactivate'
        get 'summary'
        get 'login'
        post 'check'
        post 'newgrade'
        get 'grade'
        get 'stats'
      end
      resources :polls do
        resources :answers
      end
      resources :assessments do
        resources :responses
      end
    end
  end

  resources :responses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new', via: :get
  match '/signin',  to: 'sessions#create', via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: 'StaticPages#about'
  match '/home',    to: 'users#home'
  match '/types',   to: 'StaticPages#types'

end

app/views/layouts/_footer.html.haml
// Footer
%footer.footer
  = link_to "Response Monster", root_path, class: "brand"
  %ul{ class: "footer-links pull-right" }
    %li= link_to "About", about_path
    %li.muted ·
    %li= link_to "Contact", "#"
    %li.muted ·
    %li= link_to "Sales", "/sales/index"

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container

      = link_to "ResponseMonster", root_path, class: "brand white"

      %a{:class=> "btn btn-navbar", "data-target" => ".nav-collapse" , "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      .nav-collapse.collapse
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", '#'
          - if signed_in?
            %li.dropdown
              %a{ :class => "dropdown-toggle", "data-toggle" => "dropdown", :href => "#" }
                = current_user.first_name
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Settings", current_user
                %li= link_to "Sign Out", signout_path, method: "delete"
          - else
            %li= link_to "Sign In", signin_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title
      ResponseMonster
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
    = favicon_link_tag
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
  %body
    = render "layouts/header"
    .container
      .row
        .span12
          - flash.each do |key, value|
            %div{:class => "alert alert-#{key}" }= value
      .row
        .span12
          =yield
    .container
      = render "layouts/footer"
    = javascript_include_tag "application"